"""python -m visualization {list,view,export,import} --help"""
import argparse
import json
from pathlib import Path
import time
import viser
from .data import ROOT, Motion, import_motion, read_catalog, write_catalog
from .scene import MotionScene


def select_task(catalog, task_id):
    return next(task for task in catalog['tasks'] if task['id'] == task_id)


def export(catalog, task_id=None):
    server = viser.ViserServer(host='127.0.0.1', port=8098, verbose=False)
    destination = ROOT.parent / 'assets/recordings'
    destination.mkdir(parents=True, exist_ok=True)
    try:
        for task in catalog['tasks']:
            if task_id and task['id'] != task_id:
                continue
            for variant in task['variants']:
                motion = Motion.load(ROOT / variant['file'])
                scene = MotionScene(server, motion, task)
                recording = server.get_scene_serializer()
                for frame in range(len(motion.joints)):
                    scene.update(frame)
                    recording.insert_sleep(1 / motion.fps)
                output = destination / f"{task['id']}-{variant['id']}.viser"
                output.write_bytes(recording.serialize())
                print(f'{output.name}: {output.stat().st_size / 1024:.0f} KB')
    finally:
        server.stop()
    # Derive the public manifest from the recordings actually present on disk.
    scenes = []
    for task in catalog['tasks']:
        variants = []
        for item in task['variants']:
            recording_path = f"assets/recordings/{task['id']}-{item['id']}.viser"
            if not (ROOT.parent / recording_path).exists():
                continue
            motion = Motion.load(ROOT / item['file'])
            variants.append({'id': item['id'], 'label': item['label'], 'recording': recording_path,
                             'frames': len(motion.joints), 'fps': motion.fps,
                             'duration': round(len(motion.joints) / motion.fps, 2),
                             'stage': item['stage']})
        description = task['description']
        augmentation_file = ROOT.parent / 'assets/augmentation/forehand.json'
        if task['id'] == 'forehand' and augmentation_file.exists():
            grid = json.loads(augmentation_file.read_text())
            variants = [{'id': 'augmentation', 'label': 'Contact augmentation',
                         'recording': 'assets/augmentation/forehand-base.viser',
                         'augmentationPath': 'assets/augmentation/forehand.json', 'axes': grid['axes'],
                         'frames': grid['frames'], 'fps': grid['fps'],
                         'duration': grid['frames'] / grid['fps'], 'stage': 'Augmented serve'}]
            description = 'Move the contact point in X, Y, and Z. The right arm adapts using the forehand augmentation while the rest of the motion stays fixed. Amber marks the hit target.'
        scenes.append({'id': task['id'], 'title': task['title'], 'description': description,
                       'variants': variants})
    config = {'client': 'viser-client/', 'defaultScene': 'forehand', 'scenes': scenes}
    (ROOT.parent / 'assets/viewer-manifest.js').write_text(
        '// Generated by python -m visualization export. Edit visualization/catalog.json.\n'
        'window.VICAR.viewer = ' + json.dumps(config, indent=2) + ';\n')


def view(task, variant_id, host, port):
    if task['id'] == 'forehand' and variant_id is None and (ROOT / 'motions/forehand-grid.npz').exists():
        from .forehand_view import view_forehand
        return view_forehand(host, port)
    variants = task['variants']
    if not variants:
        raise ValueError('This task has no imported recordings. Use the import command first.')
    selected = next((v for v in variants if v['id'] == variant_id), variants[0])
    if variant_id and selected['id'] != variant_id:
        raise ValueError(f'Unknown variant: {variant_id}')
    server = viser.ViserServer(host=host, port=port)
    server.gui.configure_theme(brand_color=(62, 124, 224))
    server.gui.main_panel.dock_right()
    server.gui.add_markdown(f"## {task['title']}\n{task['description']}")
    labels = {item['id']: item for item in variants}
    choose = server.gui.add_dropdown('Motion version', options=list(labels), initial_value=selected['id'])
    playing = server.gui.add_checkbox('Play', initial_value=False)
    speed = server.gui.add_slider('Playback speed', min=.25, max=2, step=.25, initial_value=1)
    motion = Motion.load(ROOT / selected['file'])
    timeline = server.gui.add_slider('Frame', min=0, max=len(motion.joints) - 1, step=1, initial_value=0)
    traces = server.gui.add_checkbox('Hand traces', initial_value=True)
    reset = server.gui.add_button('Restart')
    scene = MotionScene(server, motion, task)

    @reset.on_click
    def _(_event):
        timeline.value = 0

    # Process UI state on a single loop so rapid selections cannot mix robot
    # handles or write an old frame into the next recording.
    active = choose.value
    last_frame = -1
    deadline = time.monotonic()
    try:
        while True:
            if choose.value != active:
                playing.value = False
                active = choose.value
                motion = Motion.load(ROOT / labels[active]['file'])
                timeline.value = 0
                timeline.max = len(motion.joints) - 1
                scene = MotionScene(server, motion, task)
                last_frame = -1
            now = time.monotonic()
            if playing.value and now >= deadline:
                timeline.value = (timeline.value + 1) % len(motion.joints)
                deadline = now + 1 / (motion.fps * speed.value)
            if last_frame != timeline.value:
                scene.update(timeline.value)
                last_frame = timeline.value
            scene.show_traces(traces.value)
            time.sleep(.005)
    except KeyboardInterrupt:
        pass
    finally:
        server.stop()


def main():
    catalog = read_catalog()
    ids = [task['id'] for task in catalog['tasks']]
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    sub.add_parser('list', help='List tasks and imported recordings')
    exp = sub.add_parser('export', help='Export static Viser recordings and the website manifest')
    exp.add_argument('--task', choices=ids)
    viewer = sub.add_parser('view', help='Run a local interactive Viser player')
    viewer.add_argument('--task', choices=ids, required=True)
    viewer.add_argument('--variant')
    viewer.add_argument('--host', default='127.0.0.1')
    viewer.add_argument('--port', type=int, default=8080)
    imp = sub.add_parser('import', help='Add a saved motion to a task')
    imp.add_argument('--task', choices=ids, required=True)
    imp.add_argument('--input', type=Path, required=True)
    imp.add_argument('--id', required=True, help='Unique lowercase identifier, e.g. shift-left')
    imp.add_argument('--label', required=True)
    imp.add_argument('--stage', default='Saved augmentation')
    imp.add_argument('--fps', type=float, required=True)
    imp.add_argument('--trust-pickle', action='store_true', help='Only load a pickle you trust; pickle can execute code')
    args = parser.parse_args()
    if args.command == 'list':
        for task in catalog['tasks']:
            print(task['id'] + ': ' + (', '.join(v['id'] for v in task['variants']) or 'awaiting motion files'))
    elif args.command == 'export':
        export(catalog, args.task)
    elif args.command == 'view':
        view(select_task(catalog, args.task), args.variant, args.host, args.port)
    else:
        import re
        if not re.fullmatch('[a-z0-9]+(?:-[a-z0-9]+)*', args.id):
            parser.error('--id must contain lowercase letters, digits, and single hyphens.')
        task = select_task(catalog, args.task)
        if any(item['id'] == args.id for item in task['variants']):
            parser.error('This variant already exists. Choose a new id to preserve the existing motion.')
        motion = import_motion(args.input, args.fps, trust_pickle=args.trust_pickle)
        file = f'motions/{args.task}-{args.id}.npz'
        motion.save(ROOT / file)
        task['variants'].append({'id': args.id, 'label': args.label, 'file': file,
                                 'stage': args.stage, 'source': args.input.name})
        write_catalog(catalog)
        print(f'Imported {len(motion.joints)} frames. Run python -m visualization export --task {args.task}')


if __name__ == '__main__':
    main()
